### ISSUE TITLE
Wrong path to dist in index.js

### ISSUE THREAD

**Issue by jonchay** [esbanarango/ember-credit-card#11]
Currently in Card v2.4.0 the path to dist should be:
```js
app.import(app.bowerDirectory + '/card/dist/card.js');
```

But in the code it's set to
```
app.import(app.bowerDirectory + '/card/lib/js/card.js');
```
Which breaks in build.

**Comment by esbanarango** [comment]
Thank you for reporting this @jonchay. Would you mind creating a PR with this fix?
