### ISSUE TITLE
BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]

### ISSUE THREAD

**Issue by cvbdawson** [esbanarango/ember-credit-card#15]
I rolled back to version 2.4 and the issue was resolved.

**Comment by mwisner** [comment]
Hi @cvbdawson,

Can you provide steps to reproduce? Was this just after upgrading?

**Comment by esbanarango** [comment]
@cvbdawson could you try version `2.5.2`. 🙏
