### ISSUE TITLE
Uninstalled ember-model-validator dependency, and blueprint missing

### ISSUE THREAD

**Issue by backspace** [esbanarango/ember-credit-card#19]
Hey, I was getting this in the console after installing:

![image](https://user-images.githubusercontent.com/43280/39018613-2d17cffe-43ec-11e8-968a-abb651b7d468.png)

I wondered whether it was because of this:

![image](https://user-images.githubusercontent.com/43280/39018644-427ea67e-43ec-11e8-8353-7e2155f21328.png)

But I suspect the blueprint has been removed post-Bower? I could open a PR to remove that if that’s the case.

I was able to get past the problem by running `ember install ember-model-validator`, which isn’t something that was already present.

Thanks for your work on this, now I can try it out and see if it’ll work for our needs! 💞

**Comment by esbanarango** [comment]
@backspace Thank you for reporting this. A new version has been published with the fix: https://github.com/esbanarango/ember-credit-card/releases/tag/v2.8.0
