### ISSUE TITLE
Build throwing deprecation

### ISSUE THREAD

**Issue by dgavey** [esbanarango/ember-credit-card#5]
If you use this addon with Ember 2.8 LTS , you get a deprecation on build saying:

`DEPRECATION: Overriding init without calling this._super is deprecated. 
Please call this._super.init && this._super.init.apply(this, arguments);  addon: ember-cli-htmlbars`

You can either just upgrade the ember-cli-htmlbars to 1.08 or better or upgrade this addon's build to be Ember CLI 2.8 compliant.

Would you like a PR for one of those fixes?

**Comment by esbanarango** [comment]
Hello @dgavey. Thank you for creating this issue. Yeah a PR would be really appreciated. 👍

**Comment by dgavey** [comment]
PR has been submitted :-)
