### ISSUE TITLE
Placeholders option not working

### ISSUE THREAD

**Issue by legendac** [esbanarango/ember-credit-card#7]
Hi. I am trying to have the default expiry in the format of '••/••••' but am facing issues with the _placeholders_ option. I tried using _values_ as well. 

The rest of the options like _formSelectors_ and _width_ are working perfectly though. Below are some code references.

`{{#credit-card  form="#my-form" placeholders=ccPlaceholders }}
{{/credit-card`

`{{#credit-card  form="#my-form" values=ccPlaceholders }}
{{/credit-card`

`  ccPlaceholders: {
    number: '•••• •••• •••• ••••',
    name: 'John Doe ',
    expiry: '••/••••',
    cvc: '•••'
  },`

Thank you in advance!

**Comment by westlywright** [comment]
@legendac i was looking through the code for the same option but it does not seem to exist. From the looks of it if you want to change the placeholders you need to create the component in block form and pass through your own inputs.
