### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by dgavey** [esbanarango/ember-credit-card#9]
I upgraded to Ember 2.11.2 and I have identified an issue when the component credit-card is called.  Glimmer 2 engine is encountering an error when initializing the component and it throws a 'SyntaxError: Unexpected token u in JSON at position 0' 

I have yet to find a resolve other than removing the component.

**Comment by dgavey** [comment]
Issue seems to be around `layout: layout,` looks like that syntax isn't too friendly with Ember 2.11 I'm gonna try and make a PR around fixing that and otherwise bringing this addon up to date with both Ember and the most recent version on card.

**Comment by esbanarango** [comment]
@thank you @dgavey that would be great!
